export const VEHICLE_DATA_GET_REQUEST = "VEHICLE_DATA_GET_REQUEST";
export const VEHICLE_DATA_GET_SUCCESS = "VEHICLE_DATA_GET_SUCCESS";
export const VEHICLE_DATA_GET_FAILURE = "VEHICLE_DATA_GET_FAILURE";

export const VEHICLE_DATA_DELETE_REQUEST = "VEHICLE_DATA_DELETE_REQUEST";
export const VEHICLE_DATA_DELETE_SUCCESS = "VEHICLE_DATA_DELETE_SUCCESS";
export const VEHICLE_DATA_DELETE_FAILURE = "VEHICLE_DATA_DELETE_FAILURE";

export const VEHICLE_DATA_EDIT_REQUEST = "VEHICLE_DATA_EDIT_REQUEST";
export const VEHICLE_DATA_EDIT_SUCCESS = "VEHICLE_DATA_EDIT_SUCCESS";
export const VEHICLE_DATA_EDIT_FAILURE = "VEHICLE_DATA_EDIT_FAILURE";
